import 'zone.js';
import '@angular/compiler';
import './styles.css';
import {Component, inject, NgZone, signal} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {Router, RouterLink, RouterOutlet, provideRouter} from '@angular/router';
import {routes} from './router/routes';
import {AppStore} from './stores/app.store';

@Component({selector:'app-root', standalone:true, imports:[RouterLink, RouterOutlet], template:`
@if (!authenticated()) { <main class="login"><div class="login-art"><div class="brand-mark">KC</div><p class="eyebrow">WOOD PROCESS INTELLIGENCE</p><h1>KilnCurve<br><span>木材窑干燥优化台</span></h1><p>把含水率证据、窑炉边界和工艺判断放在同一条清晰曲线上。</p></div><form class="login-form" (submit)="login($event)"><p class="eyebrow">SECURE WORKSPACE</p><h2>进入工艺工作台</h2><label>工作邮箱<input name="email" type="email" value="admin@kilncurve.local" required></label><label>密码<input name="password" type="password" value="admin123" required></label><button class="button primary">登录工作台</button><p class="form-error">{{ error() }}</p></form></main> }
@else { <div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">KC</div><div><strong>KilnCurve</strong><small>木材窑干燥优化台</small></div></div><p class="side-label">工艺工作区</p><nav><a class="nav-item" routerLink="/kilns">▦ 窑炉档案</a><a class="nav-item" routerLink="/lots">◫ 工艺批次</a><a class="nav-item" routerLink="/readings">⌁ 含水率读数</a><a class="nav-item" routerLink="/schedules">∿ 曲线优化</a><a class="nav-item" routerLink="/audit">◌ 审计中心</a></nav></aside><main class="main"><header class="topbar"><div class="mobile-brand"><div class="brand-mark">KC</div><strong>KilnCurve</strong></div><span class="crumb">离线工艺工作台</span><div class="top-actions"><button class="icon-button" (click)="refresh()" aria-label="刷新数据">↻</button><button class="avatar" (click)="logout()" aria-label="退出登录">AD</button></div></header><nav class="mobile-nav" aria-label="移动导航"><a routerLink="/kilns">窑炉</a><a routerLink="/lots">批次</a><a routerLink="/readings">读数</a><a routerLink="/schedules">曲线</a><a routerLink="/audit">审计</a></nav><section class="content"><router-outlet/></section></main></div> }`})
class AppComponent { private readonly router=inject(Router); private readonly store=inject(AppStore); private readonly zone=inject(NgZone); readonly authenticated=signal(!!localStorage.getItem('kilncurve_token')); readonly error=signal(''); async login(event:SubmitEvent){event.preventDefault();const data=new FormData(event.target as HTMLFormElement);try{const response=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password')})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'登录失败');localStorage.setItem('kilncurve_token',body.data.token);this.zone.run(()=>this.authenticated.set(true));await this.store.refresh();await this.zone.run(()=>this.router.navigateByUrl('/kilns'))}catch(error){this.zone.run(()=>this.error.set(error instanceof Error?error.message:'登录失败'))}} refresh(){void this.store.refresh()} logout(){localStorage.removeItem('kilncurve_token');this.authenticated.set(false)}}
bootstrapApplication(AppComponent,{providers:[provideRouter(routes)]}).catch(console.error);
